-- Migration: Add pipeline and stage name columns to existing table
-- Run this ONCE against REVRYZE.RAW.GHL_OPPORTUNITIES
-- Safe to re-run (IF NOT EXISTS)

ALTER TABLE REVRYZE.RAW.GHL_OPPORTUNITIES
    ADD COLUMN IF NOT EXISTS PIPELINE_NAME STRING;

ALTER TABLE REVRYZE.RAW.GHL_OPPORTUNITIES
    ADD COLUMN IF NOT EXISTS PIPELINE_STAGE_NAME STRING;
